### PR TITLE
Copy the version mechanism from pulumi-command

### LINKED ISSUE #791: Crash when converting a Terraform project
### What happened?

I am trying to convert a Terraform project to Pulumi. I was following the official docs.

The command I ran is: `pulumi convert --from terraform --language python`

### Example

```
❯ pulumi convert --from terraform --language python
Converting from terraform...
error:

         Detected that /Users/dmitri/.pulumi/plugins/resource-terraform-v6.0.0/pulumi-resource-terraform exited prematurely.

error:          This is *always* a bug in the provider. Please report the issue to the provider author as appropriate.


error: To assist with debugging we have dumped the STDOUT and STDERR streams of the plugin:


error: panic: semver: Parse(v6.0.0): Invalid character(s) found in major number "v6"

goroutine 1 [running]:
github.com/blang/semver.MustParse({0x10450d55c, 0x6})
	/home/runner/go/pkg/mod/github.com/blang/semver@v3.5.1+incompatible/semver.go:319 +0x10c
github.com/pulumi/pulumi-terraform/v6/provider/version.init()
	/home/runner/work/pulumi-terraform/pulumi-terraform/provider/version/version.go:21 +0x2c

error:

         Detected that /Users/dmitri/.pulumi/plugins/resource-terraform-v6.0.0/pulumi-resource-terraform exited prematurely.

error:          This is *always* a bug in the provider. Please report the issue to the provider author as appropriate.


error: To assist with debugging we have dumped the STDOUT and STDERR streams of the plugin:


error: panic: semver: Parse(v6.0.0): Invalid character(s) found in major number "v6"

goroutine 1 [running]:
github.com/blang/semver.MustParse({0x10314d55c, 0x6})
	/home/runner/go/pkg/mod/github.com/blang/semver@v3.5.1+incompatible/semver.go:319 +0x10c
github.com/pulumi/pulumi-terraform/v6/provider/version.init()
	/home/runner/work/pulumi-terraform/pulumi-terraform/provider/version/version.go:21 +0x2c
```

### Output of `pulumi about`

```
❯ pulumi about
CLI
Version      3.162.0
Go Version   go1.24.2
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  python  3.162.0

Host
OS       darwin
Version  15.3
Arch     arm64

This project is written in python: executable='/opt/homebrew/bin/python3' version='3.13.3'

Backend
Name           pulumi.com
URL            https://app.pulumi.com
User           Unknown
Organizations
Token type     personal

Dependencies:
NAME          VERSION
cryptography  44.0.2
pip           25.0.1
wheel         0.45.1

Pulumi locates its logs in /var/folders/d7/25_j06f14m996cqwcd7wbg900000gn/T/ by default
warning: Failed to get information about the current stack: No current stack
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by iwahbe**
The fix for #791 is to trim the leading `v` from version numbers. The rest is to go back to general floating versions (instead of a hard-coded `6.0.0`).

Fixes #791

### CODE REVIEW

**Review by guineveresaenger — CHANGES_REQUESTED** [review]
#791 does not contain any explanation of why the crash happened.

Can we have a summary of the mechanism applied here:

1. root cause for #791
2. how this version mechanism fixes the crash 9May be obvious once (1) is explained.

We've got a lot of variation in our build assumptions, and it would be good to capture assumptions and patterns. Thank you! 🙏

**Review by VenelinMartinov — APPROVED** [review]

File: provider/version/version.go [hunk 1]
```diff
@@ -15,10 +15,12 @@
 package version
 
 import (
+	"strings"
+
 	"github.com/blang/semver"
 )
 
-var Version semver.Version = semver.MustParse(version)
+var Version semver.Version = semver.MustParse(strings.TrimPrefix(version, "v"))
```
Comment (iwahbe) [inline provider/version/version.go:23]: This fixes #791. The problem was that the release linked in a version of `v6.0.0` (not valid semver) where `6.0.0` was expected. Trimming the `"v"` solves the problem.

**Review by guineveresaenger — APPROVED** [review]
Thank you for this fix!

:shipit:
